# Generated by Django 5.2.8 on 2026-02-02 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_useractivitylog_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='النطاق')),
            ],
            options={
                'verbose_name': 'نطاق',
                'verbose_name_plural': 'النطاقات',
            },
        ),
        migrations.CreateModel(
            name='ScopeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='تفعيل النطاقات')),
            ],
            options={
                'verbose_name': 'إعدادات النطاق',
                'verbose_name_plural': 'إعدادات النطاق',
            },
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('manage_staff', 'صلاحية إنشاء مسؤول')], 'verbose_name': 'مستخدم', 'verbose_name_plural': 'المستخدمين'},
        ),
        migrations.AlterModelOptions(
            name='useractivitylog',
            options={'verbose_name': 'حركة سجل', 'verbose_name_plural': 'حركات السجل'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='occupation',
        ),
        migrations.AddField(
            model_name='customuser',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='scope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.scope', verbose_name='النطاق'),
        ),
    ]
